MS_studio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.http import HttpResponse, Http404
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^about-ms-studio/$', views.about_ms_studio, name = 'about'),
    url(r'^contacts/$', views.contacts, name = 'contacts'),
    url(r'^projects/', include ('projects_home.urls')),
    url(r'^design_interera/', include ('design_interera.urls')),
    url(r'^public/', include ('public_building.urls')),
    url(r'^price/', views.price, name='price'),
    url(r'^partner/', views.partner, name='partner'),
    url(r'^menu/', views.menu, name='menu'),

]
urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

design_interera/urls.py
from django.conf.urls import url, include
#from django.conf.urls.defaults import *
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'design_interera'
urlpatterns = [
    url(r'^$' , views.design_intr, name='design_intr'),
    url(r'^(?P<interer_id>\d+)/$' , views.detail_gallery, name = 'detail_gallery'),

]

urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projects_home/urls.py
from django.conf.urls import url, include
#from django.conf.urls.defaults import *
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'projects_home'
urlpatterns = [
    url(r'^$' , views.projects_house, name='projects_house'),
    url(r'^(?P<project_id>\d+)/$' , views.detail_gallery, name = 'detail_gallery'),

]

urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

public_building/urls.py
from django.conf.urls import url, include
#from django.conf.urls.defaults import *
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'public_building'
urlpatterns = [
    url(r'^$' , views.building, name='building'),
    url(r'^(?P<building_id>\d+)/$' , views.detail_gallery, name = 'detail_gallery'),

]

urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

partner/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Gallery(models.Model):
    class Meta:
        verbose_name = "ЛОГОТИП ПАРТНЕРОВ"
        verbose_name_plural = "Логотипы партнеров"
    img = models.ImageField(upload_to = 'partner', verbose_name="картинка/логотип")
    link = models.CharField(max_length=255, verbose_name="ссылка")

    def image_img(self):
        if self.img:
            return u'<a href="{0}" target="_blank"><img src="{0}" width="100"/></a>'.format(self.img.url)
        else:
            return '(Нет изображения)'

    image_img.short_description = 'Партнеры логотип'
    image_img.allow_tags = True

MS_studio/views.py
from django.shortcuts import render, render_to_response
from partner.models import Gallery

def index( request ):
    return render(request,'index.html')

def about_ms_studio ( request ):
    return render(request, 'about-ms-studio.html')

def contacts (request):
    return render(request, 'contacts.html' )

def price( request ):
    return render(request,'price0.html')

def partner( request ):
    items = Gallery.objects.all()
    return render(request,'partner.html', locals())

def menu( request ):
    return render(request,'base.html')

partner/views.py
from django.shortcuts import render, render_to_response

MS_studio/templates/about-ms-studio.html
{% extends "base.html" %}

{% load static %}


{% block title %}About MS-studio{% endblock title %}


{% block dop_css %}

<style>
 p{text-indent:30px; font-size:15.5px;}

</style>
{% endblock dop_css %}


{% block active_in_menu_ABOUT %}class="active"{% endblock active_in_menu_ABOUT %}


{% block content %}

<div style="background-color:#4c4b4b; width:825px; color:#ffffff; margin:0px 0px 1px 10px; padding:auto; float:left; display:inline-block;" ><b>
 <p>МS&#45;studio &#45;</b> архитектурная студия с более чем пятнадцатилетним опытом работы
 <p>Основатель студии и главный архитектор Маркова Светлана&nbsp; — автор большого числа оригинальных проектов. Под ее руководством студия разработала и реализовала множество неординарных проектов частных жилых домов и общественных объектов, множество дизайн&#45;проектов интерьеров различного назначения, среди которых офис компании BLECK SEE GATE TERMINAL, коттеджный поселок в «Сосновом берегу», офис компании OTIS, промышленный современный рынок на Овидиопольской дороге, спортивная школа «Сатори», учебный центр Эльвиры Приваловой, и многое другое… <p style="margin-top:35px"></p>
 <p>Светлана Маркова является выпускницей Одесской Академии Строительства и Архитектуры 2001 года. На сегодняшний день является членом Ассоциации Архитекторов Украины, а также имеет Квалификационный сертификат архитектора. <p style="margin-top:35px"></p>
 <p>МS&#45;studio является постоянным участником ежегодных строительных выставок BuildTech, &quot;INTER BUILD&quot;, &quot;Одесский Дом&quot;. <p style="margin-top:35px"></p>
 <p>Наши методы проектирования основаны на многолетних «наработках». Более 15&#45;ти лет мы изучаем надежность применяемых нами материалов, рациональность и технологичность решений, закладываемых в проекты домов, в проекты дизайна интерьеров.<p></p>
 <ul> Проектные решения рождаются в результате каждодневной работы по усовершенствованию проектов:
  <li>при работе со строителями мы получаем информацию, позволяющую усовершенствовать рациональность проектов и определить соотношение цены&#45;качества материалов;</li>
  <li>при работе с заказчиками, получаем информацию о практичности и удобстве решений, использованных в наших проектах;</li>
  <li>постоянно изучаем строительные материалы, предлагаемые современным рынком;</li>
  <li>уделяем большое внимание изучению новых технологий и материалов ведущих мировых брендов. Поставщики ведущих марок постоянно консультируют наших проектировщиков.</li>
 </ul> <p style="margin-top:35px"></p>
 <p>Наши проекты — это детально проработанные чертежи, в них заложены грамотные, взвешенные решения, качественные материалы, рациональные конструктивные идеи.<p style="margin-top:35px"></p>
 <p>За годы своей деятельности МS&#45;studio провела тщательную селекцию и установила партнерские отношения со строительным предприятием, зарекомендовавшей себя с лучшей стороны по качеству, быстроте и стоимости работ, чтобы гарантировать своим клиентам сдачу объектов «под ключ» с безупречным качеством, а также предоставить полный спектр обслуживания в области проектирования, строительства, дизайна и ремонта.<p style="margin-top:35px"></p>
 <ul>Наши партнеры:
  <li>проектировщики инженерных сетей и коммуникаций;</li>
  <li>отечественные и зарубежные производители отделочных материалов и мебели;</li>
  <li>фирмы, работающие в области ландшафтного дизайна;</li>
  <li>мастера художественной лепнины;</li>
  <li>художники, специализирующиеся в настенной живописи;</li>
  <li>скульпторы и реставраторы.</li>
 </ul>

</div>


  <!--  <div class="clearfix grpelem" id="u4231-3">image -->
  <div style="display:inline-block; float:right; margin-right:20px">
     <img src="{% static 'images/-c121a596e6894b2668d5cbdac9cba1485c683c9ad606cd8b50-pimgpsh_fullsize_distr.jpg' %}" alt="" width="403" height="539"/>
    </div>

{% endblock content %}

MS_studio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="html">
 <head>
  <link rel="shortcut icon" href="{% static 'images/ms-studio-favicon.ico' %}"/>
  <title>{% block title %}MS&#45;studio{% endblock title %}</title>
  <!-- CSS -->
  {% block dop_css %}{% endblock dop_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
     <!--fonts-->
  <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Chonburi" rel="stylesheet">


  <style>
 ul li a{
 margin-top:28px;
 color: #ffffff;
 font-family:'Orbitron', sans-serif;
 }

 ul li ul a {
 margin-top:3px;}


 #hr2{
 border-width: 4px;
 margin-bottom:1px;
 max-width:100%;
 margin-top:0px;
 margin-left:15px;
 margin-right:0px;
 border: none; /* Убираем границу для браузера Firefox */
 color: #f27b13; /* Цвет линии для остальных браузеров */
 background-color: #f27b13; /* Цвет линии для браузера Firefox и Opera */
 height: 3px; /* Толщина линии */
 }

 li.active a{background-color:#f27b13; padding:15px;}




  </style>


  <!-- Other scripts -->
  <script type="text/javascript">document.documentElement.className += ' js';</script>
  <!-- Latest compiled and minified JavaScript -->
 <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
 <script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 {% block dop_script %}{% endblock dop_script %}
  <!-- Other scripts -->
  <script type="text/javascript">
   document.documentElement.className += ' js';
  </script>

   </head>


 <body>

<!--begin TOP NAV BAR  bootstrap-->
<nav class="navbar " role="navigation" style="background-color:#4c4b4b; border-radius:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" style="width:400px">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" style="width:350px; margin-top:10px;" href="{% url 'index'%}">
            <img src="{% static 'images/logo0.png' %}" width="290px" height="30px"/>
            <div style="font-size:8px; color:#ffffff; font-weight: bold; font-family:'Orbitron', sans-serif;letter-spacing: 1px;">STUDIO OF ARCHITECTURE AND DESIGN COPYRIGHT <hr style="margin:-3px 0px; border-width:2px; max-width:300px;"> </div>
        </a>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects <span class="caret"></span></a>
          <ul class="dropdown-menu" >
            <li><a href="{% url 'projects_home:projects_house' %}">Проекты жилых домов</a></li>
            <li><a href="{% url 'design_interera:design_intr' %}">Дизайн интерьеров</a></li>
            <li><a href="{% url 'public_building:building' %}">Проекты общественного назначения</a></li>
            <li role="separator" class="divider"></li>
          </ul>
        </li>
        <li {% block active_in_menu_ABOUT %}{% endblock active_in_menu_ABOUT %}><a href="{% url 'about' %}">About</a></li>
        <li {% block active_in_menu_CONTACTS %}{% endblock active_in_menu_CONTACTS %}><a href="{% url 'contacts' %}">Contacts</a></li>
        <li {% block active_in_menu_PRICE %}{% endblock active_in_menu_PRICE %}><a href="{% url 'price' %}">Prices</a></li>
        <li {% block active_in_menu_PARTNERS %}{% endblock active_in_menu_PARTNERS %}><a href="{% url 'partner' %}">Partners</a></li>
        <li><img alt="Brand2" src="{% static 'images/pasted_image.jpg' %}" alt="" width="107" height="80" style="vertical-align:top"></li>
      </ul>


    </div><!-- /.navbar-collapse -->
        <hr id="hr2">
  </div><!-- /.container-fluid -->

</nav>
<!--END TOP NAV BAR  bootstrap-->
{% block content %}{% endblock content %}

 </body>
</html>

MS_studio/templates/contacts.html
{% extends "base.html" %}

{% load static %}


{% block title %}Contacts{% endblock title %}


{% block dop_css %}

<style>
    p{font-size:18px}
</style>

{% endblock dop_css %}

{% block active_in_menu_CONTACTS %}class="active"{% endblock active_in_menu_CONTACTS %}


{% block content %}
    <div style="margin: 0px 10px 0px 15px; float:left;">
     <p>Маркова Светлана, Архитектор</p>
        <p style="margin-top:10px"></p>
     <p>Украина, Одесса, ул. Маяковского 10</p>
        <p style="margin-top:10px"></p>
     <p>067&#45;92&#45;66&#45;865</p>
     <p>095&#45;048&#45;15&#45;42</p>
     <p>063&#45;839&#45;79&#45;68</p>
        <p style="margin-top:10px"></p>
     <p>email: daimonsv@rambler.ru</p>
    </div>
<div style="display:inline-block; float:right;">
  <img src="{% static 'images/google_maps.jpg' %}" width="757" height="461">
</div>
{% endblock content %}

MS_studio/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}MS-studio{% endblock title %}

{% block dop_css %}

{% endblock dop_css %}

{% block dop_script %}

<script src="{% static 'js/jquery.js' %}"></script>

{% endblock dop_script %}


{% block active_menu1 %}{% endblock active_menu1 %}


{% block content %}

<div id="carousel" class="carousel slide">

    <!-- indicators slides-->
    <ol class="carousel-indicators">
        <li class="active" data-target="#carousel" data-slide-to="0"></li>
        <li data-target="#carousel" data-slide-to="1"></li>
        <li data-target="#carousel" data-slide-to="2"></li>
    </ol>
<!-- slides -->
    <div class="carousel-inner">
        <div class="item active">
            <a href="{% url 'projects_home:projects_house' %}"><img src="{% static 'images/14.jpg' %}" alt="" height="577px"></a>
            <div class="carousel-caption">
                <h3>ПРОЕКТЫ ЖИЛЫХ ДОМОВ</h3>
            </div>
        </div>
        <div class="item">
            <a href="{% url 'design_interera:design_intr' %}"><img src="{% static 'images/a.jpg' %}" alt="" height="577px"></a>
            <div class="carousel-caption">
                <h3>ДИЗАЙН ИНТЕРЬЕРА</h3>
            </div>
        </div>
        <div class="item" style="height:577px">
            <a href="{% url 'public_building:building' %}"><img src="{% static 'images/1.jpg' %}" alt="" height="577px"></a>
            <div class="carousel-caption">
                <h3>ПРОЕКТЫ ОБЩЕСТВЕННОГО НАЗНАЧЕНИЯ</h3>
            </div>
        </div>
    </div>
<!-- Стрелки переключения слайдов -->
    <a href="#carousel" class="left carousel-control" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a href="#carousel" class="right carousel-control" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>



{% endblock content %}

MS_studio/templates/partner.html
{% extends "base.html" %}

{% load static %}

{% block title %}Partner{% endblock title %}
{% block active_in_menu_PARTNER %}class="active"{% endblock active_in_menu_PARTNER %}

{% block dop_css %}
<style>

    #mymy{
        display: inline-block;
        margin: 20px 20px 20px 20px;
	 	margin-top: 10px;
	 	position: center, center;
        background-repeat: no-repeate;
        background-size: cover;
        padding: 5px 20px 5px 20px;
}

  #mymy:hover{
	 	margin-top: 10px;
        background-repeat: no-repeate;
        background-size: cover;
        height: 350px;
	 }

   #first_otstup {margin-top:150px; margin-bottom:100px;}

   #image{
        display: inline;
        width: auto;
        max-width:220px;
        height: auto;
        max-height:220px;
        vertical-align: middle;
        margin: 5px 5px 25px 5px;
     }


</style>

{% endblock dop_css %}

{% block active_in_menu_PARTNERS %}class="active"{% endblock active_in_menu_PARTNERS %}


{% block content %}
<div style="margin-top:50px"></div>

<h1 style="text-align:center; font-size:50px">Our partners</h1>

 {% for item in items %}
        <div id="mymy" class="small-4 columns">
            <div><a href="{{item.link}}"><img  id="image" src="{{ item.img.url }}"/></a></div>
      </div>

 {% endfor %}


{% endblock content %}

MS_studio/templates/photo_detail.html
{% extends "base.html" %}
{% load static %}

{% block active_menu1 %}MuseMenuActive rounded-corners shadow{% endblock active_menu1 %}

{% block title %}{{photos.name}}{% endblock title %}

{% block dop_css %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">



<style>
.row{
    margin-left: 25px;
    margin-right: 25px;
}

  #mymy{
	 	border: 2px solid #3E3E3F;
	 	margin-top: 50px;
	 	border-radius: 4px;
	 }

   #first_otstup{
    margin-top:110px
   }

    #font{
     font-family: 'Tangerine', serif;
     font-size: 15px;
    }

      button {
  padding: 0;
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
  border: 0;
  border-radius: 3px;
  background: transparent;
  line-height: 1; }
  [data-whatinput='mouse'] button {
    outline: 0; }

 .button {
  display: inline-block;
  vertical-align: middle;
  margin: 0 0 1rem 0;
  padding: 0.5em 1.2em;
  -webkit-appearance: none;
  border: 1px solid transparent;
  border-radius: 3px;
  transition: background-color 0.25s ease-out, color 0.25s ease-out;

  line-height: 1;
  text-align: center;
  cursor: pointer;
  background-color: #f27b13;
  color: #fefefe; }
  [data-whatinput='mouse'] .button {
    outline: 0; }

.b1{
    padding-bottom: 65px;
    padding-left: 25px;
    padding-right: 25px;
    padding-top: 65px;

  body {background-color:#7f7f7f; !important}
  .button:focus,.button:hover{background-color:#aab4b5; !important}
  .just_button{background-color:#7f7f7f !important}

a.button:hover{background-color:#aab4b5}
a.just_button.button.round{background-color:#f27b13;}

 </style>

{% endblock dop_css %}


{% block content %}

<div style="margin-top:50px"></div>

{% for picture in photo_list %}
 <div style="padding: 2px -1px 2px 2px; margin:1px 1px 1px 1px; text-align:center;"><img src="{{ picture.img.url }}" alt="1" width="1250px" align="middle"></div>
<br/>
{% endfor %}

<div class="row">
  <div id="b1"><a href="../" class="just_button button round" style="font-size: 20px; text-decoration: none; color:white;  margin-left:50px;">Назад</a></div>
</div>

{% endblock content %}

MS_studio/templates/price0.html
{% extends "base.html" %}
{% load static %}

{% block active_in_menu_PRICE %}class="active"{% endblock active_in_menu_PRICE %}
{% block title %}Prices{% endblock title %}

{% block dop_css %}

<link rel="stylesheet" type="text/css" href="{% static 'css/foundation.css' %}">
<style>

 #first_otstup {margin-top:150px; margin-bottom:100px;}

</style>

{% endblock dop_css %}


{% block content %}


<!--

<div class="row" id="first_otstup" style="margin:auto; margin-top:50px;">

  <div class="small-4 columns">
    <div class="image-wrapper overlay-fade-in">
      <img src="http://xit.uz/uploads/posts/2015-12/1450437505_kollaz.png" />
      <div class="image-overlay-content">
        <h2>МИНИМАЛЬНЫЙ</h2>
        <p class="price">от 400грн./м<sup>2</sup></p>
        <a href="#" class="button">Get it</a>
      </div>
    </div>
  </div>
  <div class="small-4 columns">
    <div class="image-wrapper overlay-slide-in-left">
      <img src="https://tourneau.scene7.com/is/image/tourneau/ZEN0101011?hei=450&wid=300&fmt=png-alpha&resMode=bicub&op_sharpen=1" />
      <div class="image-overlay-content">
        <h2>СТАНДАРТ</h2>
        <p class="price">$2319.99</p>
        <a href="#" class="button">Buy Me</a>
      </div>
    </div>
  </div>
  <div class="small-4 columns">
    <div class="image-wrapper overlay-fade-in-new-background">
      <img src="https://tourneau.scene7.com/is/image/tourneau/FRK0100001?hei=450&wid=300&fmt=png-alpha&resMode=bicub&op_sharpen=1" />
      <div class="image-overlay-content">
        <h2>VIP</h2>
        <p class="price">$189,000</p>
        <a href="#" class="button">Want!</a>
      </div>
    </div>
  </div>
</div> -->

<div class="col-sm-12">
  <div class="col-sm-4 col-md-4">
    <div style="text-align:center; color: #ffffff;" class="thumbnail">
      <h3 style="background-color:#f27b13; padding:20px 10px 15px 10px; margin:0px">Базовый</h3>
      <div style="" class="caption">
        <h2 style="color:#ffffff; background-color:#e07000; margin:0px"><small style="color:#ffffff;">от</small> 390 <small style="color:#ffffff;">грн/м<sup>2</sup></small></h2>
        <p style="background-color:#d8d8d8; text-color: black">Разрабатывается стилистическое решение интерьера и предоставляется общий набор планов, чережей и экспликаций, необходимых для осуществления ремонтных работ и последующей комплектации помещения выбранным оборудование и мебелью. Включен набор разверток стен, с указанием спецификаций материалов, привязки оборудования, а также схематическими  чертежами мебели.</p>
          <h4 style="text-align:center; margin:0px">Дополнительные услуги:</h4>
          <p style="text-align:center; margin:0px">3d визуализация - от 250 грн/м</p>
          <p style="text-align:center; margin:0px">Авторский надзор - от 280 грн/м</p>
          <p style="text-align:center">Чертежи мебели цена договорная</p>
          <p style="background-color:#d8d8d8; text-color: black; margin: 0px">Срок реализации 3-4 недели</p>
          <p style="background-color:#d8d8d8; text-color: black; margin: 0px">(зависит от сложности проекта)</p>
       <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>

  <div class="col-sm-4 col-md-4">
    <div style="text-align:center; color: #ffffff;" class="thumbnail">
      <h3 style="background-color:#f27b13; padding:20px 10px 15px 10px; margin:0px">Стандарт</h3>
      <div style="" class="caption">
        <h2 style="color:#ffffff; background-color:#e07000; margin:0px"><small style="color:#ffffff;">от</small> 550 <small style="color:#ffffff;">грн/м<sup>2</sup></small></h2>
        <p style="background-color:#d8d8d8; text-color: black">Разрабатывается стилистическое решение интерьера с последующей 3d визуализации помещений, предоставляется общий набор планов, чережей и экспликаций, необходимых для осуществления ремонтных работ и последующей комплектации помещения выбранным оборудование и мебелью. Также включен набор детальных разверток стен, с подробными чертежами мебели и привязкой оборудования.</p>
          <h4 style="text-align:center; margin:0px">Дополнительные услуги:</h4>
          <p style="text-align:center; margin:0px">Авторский надзор - от 280 грн/м</p>
          <p style="text-align:center">Подбор материалов, мебели и освещения по каталогам и с выездом по магазинам и салонам.</p>
          <p style="background-color:#d8d8d8; text-color: black; margin: 0px">Срок реализации 6-9 недели</p>
          <p style="background-color:#d8d8d8; text-color: black; margin: 0px">(зависит от сложности проекта)</p>
       <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>


  <div class="col-sm-4 col-md-4">
    <div style="text-align:center; color: #ffffff;" class="thumbnail">
      <h3 style="background-color:#f27b13; padding:20px 10px 15px 10px; margin:0px">VIP</h3>
      <div style="" class="caption">
        <h2 style="color:#ffffff; background-color:#e07000; margin:0px"><small style="color:#ffffff;">от</small> 790 <small style="color:#ffffff;">грн/м<sup>2</sup></small></h2>
        <strong><p style="background-color:#d8d8d8; text-color: black">Пакет "VIP" содержит полный набор услуг, указанных для пакета "Стандарт", однако дополнен услугой "Авторский надзор", которая позволяет проводить реализацию проекта под контролем студии "MS-STUDIO". Также мы предоставим папку с технической документацией и спецификациями на осветительное, сантехническое и электрооборудование, включенное в дизайн-проект.</p></strong>
          <h4 style="text-align:center; margin:0px">Предоставляются услуги услуги:</h4>

          <p style="text-align:center; margin:0px">Подбор материалов, мебели и освещения по каталогам и с выездом по магазинам и салонам.</p>
          <p style="text-align:center; margin:0px">Выезд на объект.</p>
          <p style="background-color:#d8d8d8; text-color: black; margin: 0px">Срок реализации более 9 недели</p>
          <p style="background-color:#d8d8d8; text-color: black; margin: 0px">(зависит от обьема ремонтных работ)</p>
       <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>


<!--   <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <img src="{% static 'images/u8933.png' %}" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
-->

</div>


{% endblock content %}